# .github/workflows/delivery.yml

name: delivey


on:
  workflow_dispatch:

jobs:
  deploy-and-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Wait for services
        run: sleep 30

      - name: Run DB Migration
        run: |
          docker exec -it -u root bd_clientes /bin/bash -c "echo -e '\n[ODBC Driver 17 for SQL Server]\nDescription=Microsoft ODBC Driver 17 for SQL Server\nDriver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.6.1\nUsageCount=1' >> /etc/odbcinst.ini; /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Upt.2022 -i /tmp/clientes.sql -C"

      - name: Wait for API
        run: sleep 10

      - name: Query Prometheus Metric
        run: |
          echo "Haciendo ping a Prometheus..."
          curl -s http://localhost:9090/api/v1/query?query=up
      
      # 8. Limpiar los contenedores del runner
      - name: Shutdown services
        if: always()
        run: docker compose down
